### ISSUE TITLE
Not mobile friendly

### ISSUE THREAD

**Issue by rob84044** [maks112v/react-coming-soon#2]
The webpage in question that I am using is sendmetraveling.com. When I access this on a computer, it works just fine. But, when using a mobile device (iPhone 6) it is cut off. 

I tried putting in a CSS width of 90% on the parent container of the ComingSoon component and that didn't affect it at all.

What can we do to get this mobile-friendly?

**Comment by maks112v** [comment]
What is getting cut off?

**Comment by maks112v** [comment]
I published an update please update to the newer version

**Comment by saraspaudel** [comment]
The update didn't resolve the issue.

Website: e-code.org
Device: iPhone X, Chrome, iOS 12.4
![unnamed](https://user-images.githubusercontent.com/13654369/62810893-28f55080-bac5-11e9-8d8a-27d0051d29d6.png)
